[package]
name = "mget"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.21"
rand = "0.8.5"
smoltcp = { version = "0.12.0", features = ["proto-ipv4", "verbose", "log"] }
trust-dns = { version = "0.23.2", default-features = false }
url = "2.5.4"
